"""
detect_aruco.py

This program detects ArUco markers in a live webcam stream using OpenCV.

The detector must use the same ArUco dictionary that was used when the
markers were generated with generate_aruco.py. By default, both scripts
use the DICT_4X4_250 dictionary, which produces markers containing a
4x4 data grid surrounded by the standard ArUco black border (resulting
in a 6x6 module marker).

During execution the program:
1. Opens the specified webcam.
2. Continuously captures frames from the video stream.
3. Converts each frame to grayscale.
4. Detects ArUco markers using the selected dictionary.
5. Draws bounding boxes and IDs for detected markers.
6. Displays rejected candidate markers in red for debugging purposes.

Detected marker IDs are displayed in the video feed and printed on
screen, allowing markers generated by generate_aruco.py (via --random,
--bits, or --id) to be verified in real time.

Press 'q' or ESC to exit the program.

Examples:
python detect_aruco.py
python detect_aruco.py --dict DICT_4X4_250
python detect_aruco.py --cam 0
python detect_aruco.py --width 1920 --height 1080
"""

import argparse
import signal
import sys
import cv2

DEFAULT_DICT = "DICT_4X4_250"
DEFAULT_CAM_INDEX = 0
_stop_requested = False

def _handle_sigint(signum, frame):
    global _stop_requested
    _stop_requested = True

def get_aruco_dict(dict_name: str):
    if not hasattr(cv2, "aruco"):
        raise RuntimeError("OpenCV ArUco module not found. pip install opencv-contrib-python")
    aruco = cv2.aruco
    if not hasattr(aruco, dict_name):
        raise ValueError(f"Unknown dict '{dict_name}'. Example: DICT_4X4_250, DICT_4X4_50, ...")
    return aruco.getPredefinedDictionary(getattr(aruco, dict_name))

def main():
    global _stop_requested
    signal.signal(signal.SIGINT, _handle_sigint)

    p = argparse.ArgumentParser(description="Detect ArUco markers from a webcam feed.")
    p.add_argument("--dict", default=DEFAULT_DICT, help="ArUco dictionary name (must match generator)")
    p.add_argument("--cam", type=int, default=DEFAULT_CAM_INDEX, help="Webcam index (0 is usually built-in)")
    p.add_argument("--width", type=int, default=1280, help="Requested capture width")
    p.add_argument("--height", type=int, default=720, help="Requested capture height")
    args = p.parse_args()

    aruco_dict = get_aruco_dict(args.dict)
    parameters = cv2.aruco.DetectorParameters()
    parameters.cornerRefinementMethod = cv2.aruco.CORNER_REFINE_SUBPIX
    parameters.adaptiveThreshWinSizeMin = 3
    parameters.adaptiveThreshWinSizeMax = 35
    parameters.adaptiveThreshWinSizeStep = 4

    use_new_api = hasattr(cv2.aruco, "ArucoDetector")
    detector = cv2.aruco.ArucoDetector(aruco_dict, parameters) if use_new_api else None

    cap = cv2.VideoCapture(args.cam)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open webcam at index {args.cam}")

    cap.set(cv2.CAP_PROP_FRAME_WIDTH, args.width)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, args.height)

    print(f"Detecting with dict={args.dict}. Press Ctrl-C to quit.")

    while True:
        if _stop_requested:
            break

        ok, frame = cap.read()
        if not ok or frame is None:
            print("Failed to read frame from webcam.")
            break

        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        if use_new_api:
            corners, ids, rejected = detector.detectMarkers(gray)
        else:
            corners, ids, rejected = cv2.aruco.detectMarkers(gray, aruco_dict, parameters=parameters)

        if ids is not None and len(ids) > 0:
            cv2.aruco.drawDetectedMarkers(frame, corners, ids)
            id_list = ids.flatten().tolist()
            cv2.putText(
                frame,
                f"IDs: {id_list}",
                (10, 30),
                cv2.FONT_HERSHEY_SIMPLEX,
                1.0,
                (0, 255, 0),
                2,
                cv2.LINE_AA,
            )
        else:
            rej_n = 0 if rejected is None else len(rejected)
            cv2.putText(
                frame,
                f"No markers identified",
                (10, 30),
                cv2.FONT_HERSHEY_SIMPLEX,
                1.0,
                (0, 0, 255),
                2,
                cv2.LINE_AA,
            )

        cv2.imshow("ArUco Webcam Detection", frame)
        cv2.waitKey(1)

    cap.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    main()